nohup: ignoring input
Job "garbage_reminder (trigger: cron[hour='20', minute='0'], next run at: 2025-08-20 20:00:00 JST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/apscheduler/executors/base.py", line 131, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/opt/garbage_reminder/auto_reminder.py", line 64, in garbage_reminder
    content = generate_html(garbage_type)
  File "/opt/garbage_reminder/auto_reminder.py", line 30, in generate_html
    print(f"[{now}] HTML template loaded.")
NameError: name 'now' is not defined
nohup: ignoring input
Job "garbage_reminder (trigger: cron[hour='20', minute='0'], next run at: 2025-08-22 20:00:00 JST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/apscheduler/executors/base.py", line 131, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/opt/garbage_reminder/auto_reminder.py", line 65, in garbage_reminder
    content = generate_html(garbage_type)
  File "/opt/garbage_reminder/auto_reminder.py", line 38, in generate_html
    .replace("{{date}}", tomorrow)
TypeError: replace() argument 2 must be str, not datetime.datetime
Job "garbage_reminder (trigger: cron[hour='20', minute='0'], next run at: 2025-08-23 20:00:00 JST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/apscheduler/executors/base.py", line 131, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/opt/garbage_reminder/auto_reminder.py", line 65, in garbage_reminder
    content = generate_html(garbage_type)
  File "/opt/garbage_reminder/auto_reminder.py", line 38, in generate_html
    .replace("{{date}}", tomorrow)
TypeError: replace() argument 2 must be str, not datetime.datetime
Job "garbage_reminder (trigger: cron[hour='20', minute='0'], next run at: 2025-08-25 20:00:00 JST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/apscheduler/executors/base.py", line 131, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/opt/garbage_reminder/auto_reminder.py", line 65, in garbage_reminder
    content = generate_html(garbage_type)
  File "/opt/garbage_reminder/auto_reminder.py", line 38, in generate_html
    .replace("{{date}}", tomorrow)
TypeError: replace() argument 2 must be str, not datetime.datetime
Job "garbage_reminder (trigger: cron[hour='20', minute='0'], next run at: 2025-08-27 20:00:00 JST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/apscheduler/executors/base.py", line 131, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/opt/garbage_reminder/auto_reminder.py", line 65, in garbage_reminder
    content = generate_html(garbage_type)
  File "/opt/garbage_reminder/auto_reminder.py", line 38, in generate_html
    .replace("{{date}}", tomorrow)
TypeError: replace() argument 2 must be str, not datetime.datetime
Job "garbage_reminder (trigger: cron[hour='20', minute='0'], next run at: 2025-08-29 20:00:00 JST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/apscheduler/executors/base.py", line 131, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/opt/garbage_reminder/auto_reminder.py", line 65, in garbage_reminder
    content = generate_html(garbage_type)
  File "/opt/garbage_reminder/auto_reminder.py", line 38, in generate_html
    .replace("{{date}}", tomorrow)
TypeError: replace() argument 2 must be str, not datetime.datetime
